spring:
  kafka:
    bootstrap-servers: 192.168.3.3:9092
    consumer:
      enable-auto-commit: false
      group-id: frodo-test2
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
  redis:
    host: 192.168.3.3
    port: 6379
    database: 0
    password: # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8